events {}

http {
    server {
        listen 8080;

        location / {
            proxy_pass https://komputasitubes-production.up.railway.app;
            proxy_ssl_server_name on;
        }
    }
}