events {
    worker_connections 1024;
}

http {
    split_clients "${msec}" $random_backend {
        50% surprisebite-vercel.vercel.app;
        *   komputasitubes-production.up.railway.app;
    }

    server {
        listen 80;

        resolver 8.8.8.8 1.1.1.1 valid=300s;

        location / {
            proxy_pass https://$random_backend$request_uri;

            proxy_ssl_server_name on;

            proxy_set_header Host $random_backend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            add_header X-Served-By $random_backend always;
        }
    }
}